### PR TITLE
Fix text in Light Green mode

### PR DESCRIPTION
**Pull request by mdwalters**

### CODE REVIEW

**Comment by JoshAtticus** [comment]
md, what have you made me do??????

**Comment by JoshAtticus** [comment]
You made me merge the WHOLE bettermeower repo

**Comment by mdwalters** [comment]
i'm just going to leave meower now

**Comment by showierdata9978** [comment]
> i'm just going to leave meower now

Bruh dont

**Comment by JoshAtticus** [comment]
> i'm just going to leave meower now

I fixed the mistake, just try not to make it happen again

**Pull request closed without merging**
