### PR TITLE
Revert "Revert "Add announcement bar""

### PR DESCRIPTION
**Pull request by tnix100**
Add BetterUptime announcement thing. Originally made by @JoshAtticus but has been reverted because it needs reviews before being merged.

### CODE REVIEW

**Review by showierdata9978 — APPROVED** [review]

**Comment by JoshAtticus** [comment]
@Bloctans @MikeDev101 @zedthehedgehog @CST1229 @silvxrcat pls review

**Review by zedthehedgehog — APPROVED** [review]

**Comment by CST1229** [comment]
what does it look like?

**Comment by JoshAtticus** [comment]
> what does it look like?

good

**Review by Bloctans — APPROVED** [review]
i doubt i still need to approve this

**Pull request closed without merging**
