### PR TITLE
Revert "1.9.0"

### LINKED ISSUE #250: [master | 1.9.0] 1.9 is unfinished and extremely unstable
## Expected behavior

A finished and stable build of Meower Svelte v1.9.0, with everything tested before being put in.
## Current behavior

https://github.com/meower-media-co/Meower-Svelte/commit/02d4f8f2089bf668aa961ed5142a8a27ec7beb56#commitcomment-144251906
## Possible solution

REVERT 1.9.0 AND DO _**NOT**_ PUSH IT UNTIL IT IS READY FOR PRODUCTION!
## Steps to reproduce

1. Open Meower Svelte
2. Try uploading, logging in, etc.
## Screenshots / Logs

See https://github.com/meower-media-co/Meower-Svelte/commit/02d4f8f2089bf668aa961ed5142a8a27ec7beb56#commitcomment-144251906
## Platform info

**Meower Client**
- Meower Client Version + Build Date: Svelte v1.9.0 - 15/07/2024 (DD/MM/YYYY)

**Desktop**
 - OS: Windows 11
 - Version: 23H2
 - RAM: 16GB
 - Storage: 256GB SSD + 500GB HDD
 - CPU Architecture: x64
 
## Did I read the instructions before making this bug report?

**I have read the instructions.**

### PR DESCRIPTION
**Pull request by mybearworld**
Resolves #250

This update is not finished at all.

- Creating attachments doesn't work
- YouTube embeds refetch on new posts
- The settings aren't done
- Logging in is unstable (I had two tokens at the same time earlier, that was very weird)
- The reply syntax is atrocious

Being able to merge meower-media-co/Meower-Server#243 isn't worth Meower Svelte being very very very unstable.

https://github.com/meower-media-co/Meower-Svelte/commit/02d4f8f2089bf668aa961ed5142a8a27ec7beb56#commitcomment-144251906

### CODE REVIEW

**Comment by NotFenixio** [comment]
> * Logging in is unstable

Completely broken*

**Review by delusionsGH — APPROVED** [review]
yes, please push this

**Review by Supernoodles99 — APPROVED** [review]
hamburger

**Review by EngineerRunner — APPROVED** [review]
yuhhuh

**Review by ArrowAced — APPROVED** [review]

**Review by mybearworld — COMMENTED** [review]
merge pls

**Review by Bloctans — APPROVED** [review]
when i can i will merge this until 1.9 auth is fixed

**Comment by Bloctans** [comment]
> Resolves #250
> 
> This update is not finished at all.
> 
> * Creating attachments doesn't work
> * YouTube embeds refetch on new posts
> * The settings aren't done
> * Logging in is unstable (I had two tokens at the same time earlier, that was very weird)
> * The reply syntax is atrocious
> 
> Being able to merge [meower-media-co/Meower-Server#243](https://github.com/meower-media-co/Meower-Server/pull/243) isn't worth Meower Svelte being very very very unstable.
> 
> [02d4f8f#commitcomment-144251906](https://github.com/meower-media-co/Meower-Svelte/commit/02d4f8f2089bf668aa961ed5142a8a27ec7beb56#commitcomment-144251906)

i have fixed attachments in dev, didnt know the youtube embed issue was a thing, no idea about the settings
logging in bug isnt my department as william did that
the reply syntax is going to stay as i would add meo or roarer style replies but tnix insists we dont do that until the server supports it

**Comment by mybearworld** [comment]
> the reply syntax is going to stay as i would add meo or roarer style replies but tnix insists we dont do that until the server supports it

Yeah I really just put this at the end because I don't like it at all and I couldn't not, it's not a big issue with 1.9 of course

**Comment by tnix100** [comment]
I completely agree, this should've never been merged. While I was AFK, for some reason a bunch of unfinished PRs were merged as 1.9 and released without any review or even PR.

**Review by tnix100 — APPROVED** [review]

**Pull request merged**
