### PR TITLE
Feat: Small Posts theme

### PR DESCRIPTION
**Pull request by showierdata9978**
I only tested this in home

### CODE REVIEW

**Review by Bloctans — CHANGES_REQUESTED** [review]
can you also allow for small posts in the other themes? (not just custom themes)

**Comment by showierdata9978** [comment]
> can you also allow for small posts in the other themes? (not just custom themes)

yeah, that was just the easiest way to do it, might be easier to make all themes use the custom theme setup. just done for you

**Comment by Bloctans** [comment]
> > can you also allow for small posts in the other themes? (not just custom themes)
> 
> yeah, that was just the easiest way to do it, might be easier to make all themes use the custom theme setup. just done for you

i could try to add the selection to the custom themes modal

**Comment by Bloctans** [comment]
> > can you also allow for small posts in the other themes? (not just custom themes)
> 
> yeah, that was just the easiest way to do it, might be easier to make all themes use the custom theme setup. just done for you

nvm, when you mean custom theme setup you mean that instead of it being "blue" or "orange", its just a custom theme string?

**Review by Bloctans — APPROVED** [review]
ill just approve until that happens

**Pull request closed without merging**
