### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by roblox888i235**

### CODE REVIEW

**Review by mdwalters — COMMENTED** [review]
ok firstly, why, you literally don't need to bump the version

**Comment by roblox888i235** [comment]
idk how to make mutiple commits into one

**Comment by mdwalters** [comment]
> idk how to make mutiple commits into one

just make a separate branch for everything idk

**Comment by mdwalters** [comment]
> > idk how to make mutiple commits into one
> 
> use an ide that intergrates git instead of editing from github

or, just press the `.` key to load vscode web 🤓

**Comment by showierdata9978** [comment]
It was stated this was intentional.

**Comment by tnix100** [comment]
Also, please make sure to combine your commits into one PR. It makes it a lot easier to review.

**Pull request closed without merging**
