### PR TITLE
Add alot of pfps

### LINKED ISSUE #62: Figma Meowy personality should be added as PFPS
image

### PR DESCRIPTION
**Pull request by showierdata9978**
closes #62

### CODE REVIEW

**Comment by showierdata9978** [comment]
The Pfps are way to large, they need to be scaled down however i have no idea how to do that

**Comment by mdwalters** [comment]
attack of the grey meowy

image

**Comment by showierdata9978** [comment]
yep, thats what i expected to happen. add the BM PFP's here to make them work

**Comment by mdwalters** [comment]
ok

**Comment by mdwalters** [comment]
AAAAAA I HAVE NO IDEA WHAT TO DO

**Comment by silvxrcat** [comment]
why are they large?

**Comment by silvxrcat** [comment]
+ grey meowy still

**Comment by CST1229** [comment]
the padding needs to be added in the image

**Comment by showierdata9978** [comment]
Ye, I just pasted the svgs from figma, no idea how to add padding via figma

**Comment by CST1229** [comment]
> Ye, I just pasted the svgs from figma, no idea how to add padding via figma

i think you could just add a transparent rectangle, or maybe resize the frame and export it as svg somehow?

**Comment by showierdata9978** [comment]
image

**Comment by showierdata9978** [comment]
creating a new PR for this, as it is easier to clear em

**Comment by showierdata9978** [comment]
go to #71

**Pull request closed without merging**
