### PR TITLE
Little bit cleaner code

### PR DESCRIPTION
**Pull request by tnix100**

### CODE REVIEW

**Review by Bloctans — CHANGES_REQUESTED** [review]
check meower to know why it wouldnt work, if thats fine then ill merge

**Comment by Bloctans** [comment]
@tnix100 ^

**Comment by tnix100** [comment]
Alright, I will check it

**Comment by tnix100** [comment]
Hm, I will need to locally build, so I'll need to get npm on my laptop

**Comment by Bloctans** [comment]
im gonna unrequest changes on the main pull until we are really done

**Comment by Bloctans** [comment]
btw what i said was: wait, that review wouldnt actually work, because i could do "hi: hi" on discord and it would render as "hi"
example sentence: "for example: print("hello") would work right?" would turn into "for example"

**Comment by tnix100** [comment]
Oh I see your point

**Pull request closed without merging**
