### PR TITLE
Delete src/modpanel directory

### PR DESCRIPTION
**Pull request by Bloctans**

### CODE REVIEW

**Review by williamhorning — CHANGES_REQUESTED** [review]
Fix the issues with build before merging this, also why would you get rid of moderation functionality?

**Comment by tnix100** [comment]
> also why would you get rid of moderation functionality?

because the mod panel folder is useless, like why it is separated from the rest of the code

**Comment by williamhorning** [comment]
@tnix100 it isnt useless if it causes the build to fail when removed

**Comment by tnix100** [comment]
> @tnix100 it isnt useless if it causes the build to fail when removed

well it's not used, I odn't know why it's causing the build to fail though

**Comment by showierdata9978** [comment]
It's imported in App.svelte

**Review by williamhorning — APPROVED** [review]
works now, LGTM unless @CST1229 says otherwise

**Comment by showierdata9978** [comment]
WHY was this merged with https://github.com/meower-media-co/Meower-Svelte/pull/116

**Comment by williamhorning** [comment]
> WHY was this merged with https://github.com/meower-media-co/Meower-Svelte/pull/116 coming

That uses its own directories and doesn't use /src/modpanel

**Comment by showierdata9978** [comment]
> > WHY was this merged with #116 coming
> 
> That uses its own directories and doesn't use /src/modpanel

ah

**Pull request merged**
