### PR TITLE
Svelte 1.5

### PR DESCRIPTION
**Pull request by Bloctans**
uhhhhh check changelogs.svelte for changes

i need someone to fix the issue with image size

### CODE REVIEW

**Comment by JoshAtticus** [comment]
Does not load, gives same behaviour on iOS and Desktop.

**Comment by Bloctans** [comment]
> Does not load, gives same behaviour on iOS and Desktop.

??????????

**Comment by JoshAtticus** [comment]
> > Does not load, gives same behaviour on iOS and Desktop.
> 
> ??????????

White screen

**Comment by Bloctans** [comment]
one more bug report i cant fix and im closing the pull request

**Comment by JoshAtticus** [comment]
> > Does not load, gives same behaviour on iOS and Desktop.
> 
> ??????????

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by Bloctans** [comment]
> > > Does not load, gives same behaviour on iOS and Desktop.
> > 
> > 
> > ??????????
> 
> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

thats because cf is treating the source like HTML

**Comment by JoshAtticus** [comment]
> > > > Does not load, gives same behaviour on iOS and Desktop.
> > > 
> > > 
> > > ??????????
> > 
> > 
> > Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
> 
> thats because cf is treating the source like HTML

Oh ok, I'll run locally. Ask tnix to add NODE_VERSION = 17 to enviroment variables and set npm run build along with dist folder for preview branches.

**Comment by CST1229** [comment]
gonna be reviewing after school (because i gtg soon)

**Comment by JoshAtticus** [comment]
> gonna be reviewing after school (because i gtg soon)

wow you're in school too

**Comment by Bloctans** [comment]
i think i added webhook support
(for now comment out any code that doesnt work or fix the code)

**Comment by Bloctans** [comment]
WHEN PULLLLL

**Comment by CST1229** [comment]
> WHEN PULLLLL

i completely forgot about this

**Comment by JoshAtticus** [comment]
Remove the verified bots system, if you want to have verified bots, make an issue in server to implement it into the REST API.

**Comment by tnix100** [comment]
I'm trying to make bots a thing in CL4 port and user flags will exist, I'll make one for bots and verified bots.

**Comment by CST1229** [comment]
@Bloctans made a bunch of changes, please review

**Comment by showierdata9978** [comment]
> @Bloctans made a bunch of changes, please review

@CST1229 why remove webhooks?

**Comment by CST1229** [comment]
> @CST1229 why remove webhooks?

> i don't think allowing anonymous posts is a good idea

(and it was intentional)

**Comment by showierdata9978** [comment]
webhooks has a ip ban system, and guest usernames are completely tied to the ip of a user, so if you ban a guest user y9u basicly ip ban them. look at the src code for full the full capabilities of the ban system

**Comment by CST1229** [comment]
> ```
>     post_data["username"] = post_data.get( 
>          "username", "guest" + str(ip).replace(".", "").replace(":", "")[:6] 
>      ).replace(" ", "_")
> ```

wouldn't this create the same username for IPs like 123.123.12.23 and 123.123.122.3?

**Comment by CST1229** [comment]
Also, we should probably add a note indicating guest usernames are derived from IP addresses.

**Comment by tnix100** [comment]
I don't think guests should be able to post, it seems like it could be abused, it's also not moderated by the official moderation team, so it makes it harder to moderate. 

And another thing, if we include webhooks within the official client, we then have to include somewhere saying that their IP address will be shared with a third-party if they use guest posts.

**Comment by showierdata9978** [comment]
ye, i do plan to make it better by hopefully finding a b64`d 6 char hash

**Comment by showierdata9978** [comment]
but honestly, how rare would that be?

(255*255*255*255) + ipv6

**Comment by showierdata9978** [comment]
> I don't think guests should be able to post, it seems like it could be abused, it's also not moderated by the official moderation team, so it makes it harder to moderate. 
> 
> And another thing, if we include webhooks within the official client, we then have to include somewhere saying that their IP address will be shared with a third-party if they use guest posts.


1: still partly moderated by the moderation team, bc it does have @mod commands like discord used to

2. its on webhooks.meower.org (and hosted by me lol)

**Comment by JoshAtticus** [comment]
> > I don't think guests should be able to post, it seems like it could be abused, it's also not moderated by the official moderation team, so it makes it harder to moderate.
> > And another thing, if we include webhooks within the official client, we then have to include somewhere saying that their IP address will be shared with a third-party if they use guest posts.
> 
> 1: still partly moderated by the moderation team, bc it does have @mod commands like discord used to
> 
>     2. its on webhooks.meower.org meaning its governed by ip laws on the meower cloudflare (and hosted by me lol)
> 
>     3. its on the meower.org domain, meower does collect your ip address. i feel like that would fall under the same thing

If anything, webhooks should be hosted on the Meower Server, or included as a part of the server.

**Comment by CST1229** [comment]
> 1: still partly moderated by the moderation team, bc it does have @ mod commands like discord used to

(in case the GitHub user `mod` is reading this, that ping was probably by accident)

**Comment by showierdata9978** [comment]
> > 3. its on the meower.org domain, meower does collect your ip address. i feel like that would fall under the same thing
> 
> However, Meower does not publicize it to everyone.

ye i could also make an auto incrementing ID, that stores IP to get the id

**Comment by tnix100** [comment]
Why is this branch called `final-features-for-svelte-hopefully`? Final features before what? It should've been named something relating to it's version (1.5).

**Review by CST1229 — APPROVED** [review]
(do we still plan on allowing guest posting?)

**Comment by showierdata9978** [comment]
with recent changes yes

**Comment by CST1229** [comment]
we need reviewers

**Comment by showierdata9978** [comment]
@JoshAtticus  @tnix100 are the ones @Bloctans  requested

**Comment by showierdata9978** [comment]
im working on upgrading webhooks

**Comment by tnix100** [comment]
I am sorry for not properly reviewing yet, I will review once I'm on my PC and hopefully we can get this merged!

**Review by silvxrcat — APPROVED** [review]
SVEWLTE ONE FIVE!!! LETS GO!!!

**Comment by CST1229** [comment]
> The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)
oh sh*t

**Comment by silvxrcat** [comment]
image
??? whayt ???

**Comment by CST1229** [comment]
disabled and reenabled requiring signed commits

**Pull request merged**
