### PR TITLE
Some refinements to 1.6

### PR DESCRIPTION
**Pull request by tnix100**
Changes:
- removed Discord link button on @Discord's profile
- addded "meower.org" and "media.discordapp.net" to the whitelisted image hosts
- replaced 'Report User' on profiles with 'Moderate User' if logged into a moderator account, 'Moderate User' will bring up the moderation panel with the user's username entered and automatically get the user's info
- fixed a bug with creating posts where the 'Post' button will stay disabled after hitting the post ratelimit
- when adding a user to a chat through their profile, chats that they're already in are hidden
- when creating a chat, changing your account password, or deleting your account the submit button won't be enabled until all fields are filled out
- when creating an account you are now required to enter a password of 8 characters or more (this will soon be enforced server-side)
- swapped 'Close' and 'OK' buttons around on SwitchTheme modal so it matches other modals

Also, just a note that I think there may still be some bugs with sounds, such as home notifications still playing while not in home and BGM playing after logging out.

### CODE REVIEW

**Comment by tnix100** [comment]
So, Cloudflare is case-sensitive...

**Comment by CST1229** [comment]
also did you just ping the discord org (or does that not work)

**Review by Bloctans — APPROVED** [review]
aproval

**Comment by Bloctans** [comment]
mergin

**Pull request merged**
