### PR TITLE
Add PWA Manifest (like for real)

### PR DESCRIPTION
**Pull request by JoshAtticus**

### CODE REVIEW

**Comment by JoshAtticus** [comment]
Alright! It's ready

**Comment by JoshAtticus** [comment]
Also is it normal for the Cloudflare pages build to end up with a black screen?

**Comment by CST1229** [comment]
> Also is it normal for the Cloudflare pages build to end up with a white screen?

yes, as it's trying to run the unbuilt source code and the browser doesn't know what to do with .svelte files

**Comment by CST1229** [comment]
@JoshAtticus but aren't there more requirements for PWAs (like a 512x512 icon and a service worker)? was this tested?

**Comment by JoshAtticus** [comment]
> @JoshAtticus but aren't there more requirements for PWAs (like a 512x512 icon and a service worker)? was this tested?

No, it has a 512x512 icon, and service worker is only needed for push notifications and offline support, both things Meower Svelte doesn't need.

**Comment by CST1229** [comment]
> > @JoshAtticus but aren't there more requirements for PWAs (like a 512x512 icon and a service worker)? was this tested?
> 
> No, it has a 512x512 icon, and service worker is only needed for push notifications and offline support, both things Meower Svelte doesn't need.

1. Where?
2. https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

**Comment by JoshAtticus** [comment]
> > > @JoshAtticus but aren't there more requirements for PWAs (like a 512x512 icon and a service worker)? was this tested?
> > 
> > 
> > No, it has a 512x512 icon, and service worker is only needed for push notifications and offline support, both things Meower Svelte doesn't need.
> 
> 1. Where?
> 2. https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs
> 
> 

_**To allow the app to work offline**_ Meower doesn't work offline

**Comment by CST1229** [comment]
> And ugh the 512x512 icon didn't upload, also not necessary anyways

Anyways, does it work for you? I don't see any download prompt on svelte.meower.org on Chrome (but I do on TurboWarp so I know it's not my browser not supporting PWAs).

**Comment by JoshAtticus** [comment]
> > And ugh the 512x512 icon didn't upload, also not necessary anyways
> 
> Anyways, does it work for you? I don't see any download prompt on svelte.meower.org on Chrome (but I do on TurboWarp so I know it's not my browser not supporting PWAs).

I didn't add that feature, just click the three dots and then add to home screen

**Comment by JoshAtticus** [comment]
Ah $^@* it doesn't work on android, only iOS

**Comment by JoshAtticus** [comment]
Will fix

**Comment by CST1229** [comment]
> > > And ugh the 512x512 icon didn't upload, also not necessary anyways
> > 
> > 
> > Anyways, does it work for you? I don't see any download prompt on svelte.meower.org on Chrome (but I do on TurboWarp so I know it's not my browser not supporting PWAs).
> 
> I didn't add that feature, just click the three dots and then add to home screen

This is all that shows for me there:

**Comment by JoshAtticus** [comment]
> > > > And ugh the 512x512 icon didn't upload, also not necessary anyways
> > > 
> > > 
> > > Anyways, does it work for you? I don't see any download prompt on svelte.meower.org on Chrome (but I do on TurboWarp so I know it's not my browser not supporting PWAs).
> > 
> > 
> > I didn't add that feature, just click the three dots and then add to home screen
> 
> This is all that shows for me there: 

Need to move .webmanifest file to root

**Comment by JoshAtticus** [comment]
Actually, I don't. I just don't know why it won't work

**Comment by CST1229** [comment]
I did some changes (the start_url manifest option is required so i added it, remade a 512x512 icon, moved manifest to root and added a service worker (i think it should still display a connection error screen instead of a default browser message)) and now it works for me.

**Comment by JoshAtticus** [comment]
> I did some changes (the start_url manifest option is required so i added it, remade a 512x512 icon, moved manifest to root and added a service worker (i think it should still display a connection error screen instead of a default browser message)) and now it works for me. 

Woohoo! I'll need to change ?v2=true on all of the links to ?v3=true so it gets refreshed.

**Comment by JoshAtticus** [comment]
Youuuuuuuuuuuuuuuu, deleted the manifest folder? Now it isn't going to work because that's what index.html is referencing

**Comment by JoshAtticus** [comment]
and you deleted ?v2=true? now browsers are going to use old cached icons.

**Comment by JoshAtticus** [comment]
Bruh lemme fix that real quick.

**Comment by JoshAtticus** [comment]
I had that stuff there for a reason.

**Comment by CST1229** [comment]
> Youuuuuuuuuuuuuuuu, deleted the manifest folder? Now it isn't going to work because that's what index.html is referencing

I moved it to public (there, stuff stays where it is and doesn't get mixed up during the compilation step).

**Comment by CST1229** [comment]
> and you deleted ?v2=true? now browsers are going to use old cached icons.

Do browsers cache 404s?

**Comment by JoshAtticus** [comment]
> > and you deleted ?v2=true? now browsers are going to use old cached icons.
> 
> Do browsers cache 404s?

It's not a 404

**Comment by JoshAtticus** [comment]
> > Youuuuuuuuuuuuuuuu, deleted the manifest folder? Now it isn't going to work because that's what index.html is referencing
> 
> I moved it to public (there, stuff stays where it is and doesn't get mixed up during the compilation step).

No, after moving manifest back, where index.html references it to be, the "Add to home screen" popup appears

**Comment by JoshAtticus** [comment]
Don't undo it that's how it's actually meant to be, I understand what I am doing.

**Comment by CST1229** [comment]
> Don't undo it that's how it's actually meant to be, I understand what I am doing.

Note that, previously, most existing directories were kept when the build action ran, which might have appeared to make things work while they actually shouldn't have.

**Pull request merged**
