### PR TITLE
Webhooks in Svelte

### PR DESCRIPTION
**Pull request by silvxrcat**
parse "Webhooks" user. since the user parsed usually doesn't exist, the pfp is randomized.

### CODE REVIEW

**Comment by silvxrcat** [comment]
tried to optimize retrieval code a bit for future usage

**Comment by Bloctans** [comment]
transfering to bettermeower.

**Comment by Bloctans** [comment]
nvm

**Comment by silvxrcat** [comment]
> transfering to bettermeower.

lmao

**Comment by Bloctans** [comment]
but still this is planned for bettermeower. still fine with me

**Review by Bloctans — APPROVED** [review]
why am i thinking this is for bettermeower

**Comment by mdwalters** [comment]
BETTERMEOWER THE BEST MEOWER CLIENT EVER

**Comment by showierdata9978** [comment]
Webhooks can have a PFP. it also needs to have a [WEBHOOKS] badge so people know its from webhooks

**Comment by silvxrcat** [comment]
> Webhooks can have a PFP. it also needs to have a [WEBHOOKS] badge so people know its from webhooks
> 
> send a get request to webhooks.meower.org/pfps/

1. already did badge
2. webhooks.meower.org/pfps/ is broken
image

did you even look at my code?

**Comment by CST1229** [comment]
i don't think the pfp should be randomized (probably instead derived from the username somehow or just static)

**Comment by silvxrcat** [comment]
> i don't think the pfp should be randomized (probably instead derived from the username somehow or just static)

should i change it then? if you feel like it should just be static then yeah ill change it

**Comment by showierdata9978** [comment]
> > Webhooks can have a PFP. it also needs to have a [WEBHOOKS] badge so people know its from webhooks
> > send a get request to webhooks.meower.org/pfps/
> 
>     1. already did badge
> 
>     2. webhooks.meower.org/pfps/ is broken
>        image
> 
> 
> did you even look at my code?

thats because the user does not exist in the current runtime of webhooks. you need to send a msg first

**Comment by silvxrcat** [comment]
> > > Webhooks can have a PFP. it also needs to have a [WEBHOOKS] badge so people know its from webhooks
> > > send a get request to webhooks.meower.org/pfps/
> > 
> > 
> > ```
> > 1. already did badge
> > 
> > 2. webhooks.meower.org/pfps/ is broken
> >    image
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > did you even look at my code?
> 
> thats because the user does not exist in the current runtime of webhooks. you need to send a msg first

do we reeeeeeally have to though

**Review by tnix100 — COMMENTED** [review]
Could we possibly implement something allows Webhooks to have a custom pfp? And for requests that don't have a pfp, I think we should just use gray meowy

**Comment by silvxrcat** [comment]
> Could we possibly implement something allows Webhooks to have a custom pfp? And for requests that don't have a pfp, I think we should just use gray meowy

Webhooks apparently *do*, however the webhook pfp system is kind of odd and I would rather just implement a random profile picture/static one.

**Comment by showierdata9978** [comment]
Its not really odd. its just that the pfps are stored at runtime insted of in the user DB

**Comment by tnix100** [comment]
Pfps should be per message

**Comment by showierdata9978** [comment]
> Pfps should be per message

webhooks is an API, i dont have access to the post ID

**Comment by silvxrcat** [comment]
ill edit so that it's just static for now, i guess

**Comment by showierdata9978** [comment]
just send a get request when a  new post pops up if it has not been cashed, thats all that needs to happen

**Comment by silvxrcat** [comment]
> just send a get request when a  new post pops up if it has not been cashed, thats all that needs to happen

i only made it static *for now*, im going to try to achieve this later

**Review by CST1229 — APPROVED** [review]
will need to be updated in 1.5 for the new badge system
(also, you don't need to add `* in Svelte` or `add * to Svelte` to PR and branch titles; we know what repo we're on)

**Pull request merged**
