### PR TITLE
Fix a spelling error

### PR DESCRIPTION
**Pull request by derpygamer2142**

### CODE REVIEW

**Comment by theotherhades** [comment]
Not needed, this is simply a difference between US and UK English. Not a spelling mistake.

**Comment by CST1229** [comment]
Yea, this is a British vs. American English difference, but most other MMC repos spell it the American way (and I just prefer that spelling).

**Review by CST1229 — APPROVED** [review]

**Comment by theotherhades** [comment]
Personally I think it's pretty pedantic but makes sense.

**Comment by derpygamer2142** [comment]
really? i did not know that

**Comment by showierdata9978** [comment]
I also prefer American spelling (as im texan lol)

**Comment by derpygamer2142** [comment]
oh ok

**Comment by tnix100** [comment]
I think this was an intentional thing by William to change to British English for LICENCE. I like British English more but I can understand since Meower is mainly in the US and we mainly use American English in our repos.

**Comment by showierdata9978** [comment]
#108 i did it British way; because GitHub shows it when doing it the British way

**Review by showierdata9978 — APPROVED** [review]

**Review by tnix100 — APPROVED** [review]

**Comment by showierdata9978** [comment]
merge?

**Comment by derpygamer2142** [comment]
oh cool

**Pull request merged**
