### PR TITLE
auto-reconnection, and some other small things

### PR DESCRIPTION
**Pull request by tnix100**
Changes:
- auto-reconnection
- fixed bug where it will say you've been disconnected while logging out
- fixed bug where if you load a post from the API at the same time it was sent over CL, the post will be duplicated
- more rounded corners on containers
- some other small things (just check the code lol)

### CODE REVIEW

**Comment by CST1229** [comment]
the reconnecting page probably shouldn't jumpscare the user by it appearing (maybe just a popup in the corner? though this probably isn't very important).  
also, are text inputs not having more rounded corners intentional? though i don't mind since it makes them a bit more distinguishable from containers

**Comment by tnix100** [comment]
> 

I made it so it goes to the full screen connecting because it'll need to re-login to their account and having it as a separate thing will cause more duplicate code. It also needs to reload the current page they're on which this is an easy way to do that.

I kind of intentionally didn't round text boxes and buttons, because it helps distinguish them from containers.

**Comment by tnix100** [comment]
Another commit just made to make all theme previews look the same with the same resolution and content.

**Review by Bloctans — APPROVED** [review]
ooooo, ill wait for cst to approve then ill merge

**Comment by tnix100** [comment]
> > Another commit just made to make all theme previews look the same with the same resolution and content.
> > The timestamps are at like 3am lol, oh well.
> 
> the ideal solution would be to make the previews dynamic and an svg, kinda like scratch addons  however, that would probably take a while to do

Yeah, may be something we can implement later on, it will require some work.

**Review by CST1229 — APPROVED** [review]

**Pull request merged**
