### PR TITLE
Add New PFPS

### LINKED ISSUE #62: Figma Meowy personality should be added as PFPS
image

### PR DESCRIPTION
**Pull request by showierdata9978**
closes #62  

successor to #64

### CODE REVIEW

**Review by silvxrcat — DISMISSED** [review]
size consistency of meowy is bugged

**Comment by showierdata9978** [comment]
> size consistency of meowy is bugged

i did what i had to, and that is shrink some of em

**Comment by JoshAtticus** [comment]
Because meower svelte does not have the newer BetterMeower pfps, this pr makes meower svelte pfps incompatible with BetterMeower and vice versa.

**Review by JoshAtticus — CHANGES_REQUESTED** [review]
Add the new BetterMeower pfps to avoid breaking compatibility.

**Comment by showierdata9978** [comment]
> Add the new BetterMeower pfps to avoid breaking compatibility.

BM is not active, so it really does not matter, if you want to do this then make a pr to this branch

**Comment by JoshAtticus** [comment]
> > Add the new BetterMeower pfps to avoid breaking compatibility.
> 
> BM is not active, so it really does not matter, if you want to do this then make a pr to this branch

It does matter, because when it becomes active again (after CL4 port), it will break a lot. According to tnix, CL4 svelte will be done by the end of January.

**Comment by showierdata9978** [comment]
> > > Add the new BetterMeower pfps to avoid breaking compatibility.
> > 
> > 
> > BM is not active, so it really does not matter, if you want to do this then make a pr to this branch
> 
> It does matter, because when it becomes active again (after CL4 port), it will break a lot. According to tnix, CL4 svelte will be done by the end of January.

> if you want to do this then make a pr to this branch

**Comment by JoshAtticus** [comment]
> > > > Add the new BetterMeower pfps to avoid breaking compatibility.
> > > 
> > > 
> > > BM is not active, so it really does not matter, if you want to do this then make a pr to this branch
> > 
> > 
> > It does matter, because when it becomes active again (after CL4 port), it will break a lot. According to tnix, CL4 svelte will be done by the end of January.
> 
> > if you want to do this then make a pr to this branch

No you need to fix the issue in this branch

**Comment by showierdata9978** [comment]
@CST1229 what do you think of above, i don't see it as important. because bm pfps cant be seen or selected rn anyway. Josh can add the pfps if he wants do but idc about doin it myself

**Comment by JoshAtticus** [comment]
> @CST1229 what do you think of above, i don't see it as important. because bm pfps cant be seen or selected rn anyway. Josh can add the pfps if he wants do but idc about doin it myself

Well then that will break Meower Svelte, because BetterMeower pfps show as the new pfps, it is important.

**Comment by showierdata9978** [comment]
> > @CST1229 what do you think of above, i don't see it as important. because bm pfps cant be seen or selected rn anyway. Josh can add the pfps if he wants do but idc about doin it myself
> 
> Well then that will break Meower Svelte, because BetterMeower pfps show as the new pfps, it is important.


BM is your client; it's not my job to have compatibility with it. Even more so I don't even have the BM pfps

**Comment by JoshAtticus** [comment]
> > > @CST1229 what do you think of above, i don't see it as important. because bm pfps cant be seen or selected rn anyway. Josh can add the pfps if he wants do but idc about doin it myself
> > 
> > 
> > Well then that will break Meower Svelte, because BetterMeower pfps show as the new pfps, it is important.
> 
> BM is your client; it's not my job to have compatibility with it. Even more so I don't even have the BM pfps

I can send you the BetterMeower pfps, there are 5.

**Comment by showierdata9978** [comment]
Screenshot_20230113-192120

**Comment by JoshAtticus** [comment]
>~snip~

No, that won't work, the PFP picker is not going to show them. I am not adding an additional week of stress to my already cluttered and stressful holidays to make it work either.

**Comment by tnix100** [comment]
Maybe we should just decide on all of the default pfps we're going to have in CL4 port and later and then just don't change them. Custom pfps will be a thing in CL4 port and later, so it doesn't make much sense to keep adding more and more default pfps.

**Comment by silvxrcat** [comment]
we should have like a few default pfps which in reality set your custom pfp .png data to that image. once cl4 port, bettermeower pfps will not break and will instead just show a .png of the user instead of a pfp_data int

**Comment by tnix100** [comment]
> 

nah, since most of the default pfps are SVGs

**Comment by showierdata9978** [comment]
This pr is for 1.6

**Comment by JoshAtticus** [comment]
> 

That would work perfectly, because then I can add BetterMeower pfps and not have them break svelte.

**Comment by tnix100** [comment]
> > 
> 
> That would work perfectly, because then I can add BetterMeower pfps and not have them break svelte.

Default pfps used in Meower Svelte shouldn't be file uploads though, since most are SVGs and will use a ton of bandwidth uploading default pfps.

The current way I have it in CL4 port is pfps/icons have 2 properties, 1 for the type and 1 for the data, type can either be 0 for default pfp or 1 for custom pfp, then data is either like it is now for default pfps or a partial upload object for custom pfps.

**Comment by showierdata9978** [comment]
It's svgs because of scratch

**Comment by tnix100** [comment]
> It's svgs because of scratch

And why should it not be an SVG in svelte? It's far higher quality than a PNG or JPEG.

Also we have to keep compatibility with Scratch throughout CL4 port.

**Comment by showierdata9978** [comment]
> > It's svgs because of scratch
> 
> And why should it not be an SVG in svelte? It's far higher quality than a PNG or JPEG.
> 
> Also we have to keep compatibility with Scratch throughout CL4 port.

Yeah ik, also svgs fail to render on gh for meh

**Comment by CST1229** [comment]
> > > 
> > 
> > 
> > That would work perfectly, because then I can add BetterMeower pfps and not have them break svelte.
> 
> Default pfps used in Meower Svelte shouldn't be file uploads though, since most are SVGs and will use a ton of bandwidth uploading default pfps.
> 
> The current way I have it in CL4 port is pfps/icons have 2 properties, 1 for the type and 1 for the data, type can either be 0 for default pfp or 1 for custom pfp, then data is either like it is now for default pfps or a partial upload object for custom pfps.

We could also add an option for a PFP URL.

**Comment by JoshAtticus** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > That would work perfectly, because then I can add BetterMeower pfps and not have them break svelte.
> 
> > 
> 
> > Default pfps used in Meower Svelte shouldn't be file uploads though, since most are SVGs and will use a ton of bandwidth uploading default pfps.
> 
> > 
> 
> > The current way I have it in CL4 port is pfps/icons have 2 properties, 1 for the type and 1 for the data, type can either be 0 for default pfp or 1 for custom pfp, then data is either like it is now for default pfps or a partial upload object for custom pfps.
> 
> 
> 
> We could also add an option for a PFP URL.

Or use gravatar

**Comment by showierdata9978** [comment]
Why is this PR still blocked. the issue has been resolved. and the thing being discussed is not the point of this PR

**Comment by JoshAtticus** [comment]
> Why is this PR still blocked. the issue has been resolved. and the thing being discussed is not the point of this PR

i forgot

**Comment by CST1229** [comment]
kinda nitpicking here, this pfp could be made larger (making the meowy about the same size as the others)
image

**Comment by showierdata9978** [comment]
That one is sticking out; if I did not change it's size it would look odd

**Comment by mdwalters** [comment]
> Screenshot_20230113-192120

t-mobile

**Comment by JoshAtticus** [comment]
> > ~snip~
> 
> t-mobile

telstra better

**Comment by silvxrcat** [comment]
might close this PR because we do not need a full page of default profile pictures when APIv1/CL4 port/Beta 6 is honestly around the corner, which will have profile picture upload support. i don't care about the support of the old scratch clients as no one really uses them anyways and they're going to be depreciated soon. we should not add more default profile pictures until Beta 6, and users don't need another 20 profile pictures anyway.

if you dislike my thoughts go ahead and complain about it, but this PR just doesn't make sense due to future features.

**Comment by JoshAtticus** [comment]
> if you dislike my thoughts go ahead and complain about it, but this PR just doesn't make sense due to future features.

I did the opposite of that

**Comment by mdwalters** [comment]
> might close this PR because we do not need a full page of default profile pictures when APIv1/CL4 port/Beta 6 is honestly around the corner, which will have profile picture upload support. i don't care about the support of the old scratch clients as no one really uses them anyways and they're going to be depreciated soon. we should not add more default profile pictures until Beta 6, and users don't need another 20 profile pictures anyway.
> 
> if you dislike my thoughts go ahead and complain about it, but this PR just doesn't make sense due to future features.

i wish you can react the skull emoji

**Comment by mdwalters** [comment]
> > > ~snip~
> > 
> > 
> > t-mobile
> 
> telstra better

t-mobile gets a data breach almost every day

**Comment by showierdata9978** [comment]
> might close this PR because we do not need a full page of default profile pictures when APIv1/CL4 port/Beta 6 is honestly around the corner, which will have profile picture upload support. i don't care about the support of the old scratch clients as no one really uses them anyways and they're going to be depreciated soon. we should not add more default profile pictures until Beta 6, and users don't need another 20 profile pictures anyway.
> 
> if you dislike my thoughts go ahead and complain about it, but this PR just doesn't make sense due to future features.

cl4 is a month away, maybe 2. I think its fair to add more meowy pfps

**Comment by mdwalters** [comment]
> cl4 is a month away

tnix says it's going to be released at the end of the this month, so, it's a week away, not a month

**Comment by showierdata9978** [comment]
After then, it is still a month away bc of rewrites, that are needed

**Comment by mdwalters** [comment]
ok

**Comment by JoshAtticus** [comment]
> > might close this PR because we do not need a full page of default profile pictures when APIv1/CL4 port/Beta 6 is honestly around the corner, which will have profile picture upload support. i don't care about the support of the old scratch clients as no one really uses them anyways and they're going to be depreciated soon. we should not add more default profile pictures until Beta 6, and users don't need another 20 profile pictures anyway.
> > 
> > if you dislike my thoughts go ahead and complain about it, but this PR just doesn't make sense due to future features.
> 
> cl4 is a month away, maybe 2. I think its fair to add more meowy pfps 

No it's not, it's already finished. Just waiting on CL4 port Svelte, which is planned to be done by the end of the month

**Comment by silvxrcat** [comment]
> > > might close this PR because we do not need a full page of default profile pictures when APIv1/CL4 port/Beta 6 is honestly around the corner, which will have profile picture upload support. i don't care about the support of the old scratch clients as no one really uses them anyways and they're going to be depreciated soon. we should not add more default profile pictures until Beta 6, and users don't need another 20 profile pictures anyway.
> > > if you dislike my thoughts go ahead and complain about it, but this PR just doesn't make sense due to future features.
> > 
> > 
> > cl4 is a month away, maybe 2. I think its fair to add more meowy pfps
> 
> No it's not, it's already finished. Just waiting on CL4 port Svelte, which is planned to be done by the end of the month

yeah, i think im going to close this.

**Comment by showierdata9978** [comment]
This is cst's project tho, so

**Comment by tnix100** [comment]
> > > might close this PR because we do not need a full page of default profile pictures when APIv1/CL4 port/Beta 6 is honestly around the corner, which will have profile picture upload support. i don't care about the support of the old scratch clients as no one really uses them anyways and they're going to be depreciated soon. we should not add more default profile pictures until Beta 6, and users don't need another 20 profile pictures anyway.
> > > if you dislike my thoughts go ahead and complain about it, but this PR just doesn't make sense due to future features.
> > 
> > 
> > cl4 is a month away, maybe 2. I think its fair to add more meowy pfps
> 
> No it's not, it's already finished. Just waiting on CL4 port Svelte, which is planned to be done by the end of the month

It's mostly done, I would say it's stable (up until today where I broke user sessions and CL events, sorry). Right now it's just adding features and cleaning up code/API endpoints. Tomorrow it'll be back in a stable state and can start to be implemented into clients. The beta server is delayed a bit, and Idk when it'll be out.

**Comment by showierdata9978** [comment]
And iv already implemented the new PFPs into SvelteKit. so if the pfps are not added, a official client does not have support lmao

**Comment by silvxrcat** [comment]
> This is cst's project tho, so

it’s a pull request…

**Comment by showierdata9978** [comment]
> > This is cst's project tho, so
> 
> it’s a pull request…

Im talking about Meower-Svelte

**Comment by JoshAtticus** [comment]
> And iv already implemented the new PFPs into SvelteKit. so if the pfps are not added, a official client does not have support lmao

Same with BetterMeower, except the Meower Svelte team chose to add BetterMeower pfps, NOT while trying to merge a whole new release.

**Pull request closed without merging**
