### PR TITLE
Svelte 1.6

### PR DESCRIPTION
**Pull request by silvxrcat**
Draft pull request for Meower 1.6

### CODE REVIEW

**Comment by silvxrcat** [comment]
PostList PR needs to still be finished, + fix "add more pfps" PR to add to develop

**Comment by showierdata9978** [comment]
Also blocked by #71

**Comment by JoshAtticus** [comment]
#69 nice

**Comment by tnix100** [comment]
> showier do we really need to have a bunch of new pfps when cl4 port is around the corner

Well, CL4 port will still have default pfps, but we shouldn't add anymore after CL4 port releases.

**Comment by silvxrcat** [comment]
> > showier do we really need to have a bunch of new pfps when cl4 port is around the corner
> 
> 
> 
> Well, CL4 port will still have default pfps, but we shouldn't add anymore after CL4 port releases.

i know, but we really dont need anymore ig

**Comment by JoshAtticus** [comment]
I agree too

**Comment by JoshAtticus** [comment]
I'm in the credits? 🥲

**Comment by JoshAtticus** [comment]
> Also blocked by #71 

#71 would be blocked by this because this pr came first

**Comment by showierdata9978** [comment]
> > Also blocked by #71
> 
> #71 would be blocked by this because this pr came first

That is the second PR for that. #64 was the original PR

**Comment by JoshAtticus** [comment]
> > > Also blocked by #71
> > 
> > 
> > #71 would be blocked by this because this pr came first
> 
> That is the second PR for that. #64 was the original PR

Yeah but that was closed, this PR would be blocked by #64 if it was still open

**Comment by tnix100** [comment]
No join message and constant notification sound in livechat

https://user-images.githubusercontent.com/61485190/226518738-4b2bf6b2-6cbd-4c24-a1b5-27a96eb2cde9.mp4

**Comment by CST1229** [comment]
just realized that this PR is *n i c e*

**Comment by CST1229** [comment]
i think it's because i said "Should resolve https://github.com/meower-media-co/Meower-Svelte/pull/69#issuecomment-1477273311", and that made GH think the PR resolves this PR

**Comment by Bloctans** [comment]
im currently making a branch to add onto 1.6

**Comment by Bloctans** [comment]
#145

**Comment by CST1229** [comment]
still blocked by bgm-related server changes (to disable bgm for existing recent accounts, since svelte didn't have bgm before and it's enabled by default on the server), undrafting for reviews

**Comment by CST1229** [comment]
> showier do we really need to have a bunch of new pfps when cl4 port is around the corner

5 months later:

**Review by CST1229 — APPROVED** [review]

**Review by tnix100 — APPROVED** [review]

**Comment by CST1229** [comment]
nice
image

**Review by showierdata9978 — APPROVED** [review]
other then @`html` yes

**Review by MikeDev101 — APPROVED** [review]
LGTM.

**Review by JoshAtticus — APPROVED** [review]
sus

**Comment by Bloctans** [comment]
merge when???

**Comment by mdwalters** [comment]
> other then @`html` yes

calm down showier it uses cst's escape hack geez

**Comment by MikeDev101** [comment]
Didn't have tnix available to know how to update newer-ish accounts, so I just turned off BGM for all accounts in the database. This PR _should_ be ready to merge.

**Comment by silvxrcat** [comment]
we should def merge, is everything like changelog ok??? we should make sure that everything is correct before we merge

we should also announce this lol :3

**Comment by MikeDev101** [comment]
> we should def merge, is everything like changelog ok??? we should make sure that everything is correct before we merge
> 
> we should also announce this lol :3

Changelog appears to have sufficient details. Going to make the announcement now.

**Comment by silvxrcat** [comment]
ok i think everything looks good. will merge if everyone's fine

**Comment by silvxrcat** [comment]
merging now!!!!!! yay

**Pull request merged**
