### PR TITLE
Moderation panel!

### PR DESCRIPTION
**Pull request by CST1229**
(this should have been added earlier...)

Also misc changes to stuff; see the commit log.

### CODE REVIEW

**Comment by MikeDev101** [comment]
Me with MeowyMod rn: 
image

**Comment by showierdata9978** [comment]
MM with bridges:

**Comment by showierdata9978** [comment]
resub to thread, clicked the wrong email button

**Comment by showierdata9978** [comment]
That did not fix it... your not checking if they can get IP's

**Comment by CST1229** [comment]
> That did not fix it... your not checking if they can get IP's

i thought i did (i don't have a l1 account to test though)

**Comment by showierdata9978** [comment]
Screenshot_20230323-133630

**Comment by showierdata9978** [comment]
Screenshot_20230323-133929

**Comment by showierdata9978** [comment]
works
Screenshot_20230323-134541

**Comment by showierdata9978** [comment]
My review still stands. Please make it look at least a bit better on mobile.

**Review by showierdata9978 — CHANGES_REQUESTED** [review]
^

**Review by showierdata9978 — APPROVED** [review]

**Comment by williamhorning** [comment]
@CST1229 can this be merged?

**Comment by CST1229** [comment]
> @CST1229 can this be merged?

i guess

**Pull request merged**
