### PR TITLE
Things i had on the todo list i never got to doing

### PR DESCRIPTION
**Pull request by Bloctans**
- tiny crown on chat owner
- "fix" terrible codebase (More specifically Modals)
- add to chat button on profiles 
- add users to gc via search
- Theme modal (for oobe and settings)
- OOBE
- image button (simpler way to upload images)
- BGM
- BGM + SFX modal
- basic modal
- authors for music in bgm
- disable bgm by default

### CODE REVIEW

**Comment by Bloctans** [comment]
issue: bgm isnt working. idk why

**Comment by Bloctans** [comment]
good, the reason i didnt want it as json was because it felt too storage intensive.

**Comment by Bloctans** [comment]
the issue is that cf pages seems to be failing

**Comment by Bloctans** [comment]
list of complaints i guess:
- why no more crown meowy?
- the reason the custom theme wasnt json was because i thought json was too storage intensive, but i guess that doesnt matter
- cf pages wont build

**Review by Bloctans — COMMENTED** [review]
https://github.com/meower-media-co/Meower-Svelte/pull/145#issuecomment-1574320285

**Comment by CST1229** [comment]
> why no more crown meowy?

in light mode, the crown is less visible (because it's bright yellow), and i think having just a crown icon would be clearer

> the reason the custom theme wasnt json was because i thought json was too storage intensive

it's only a few bytes

> cf pages wont build (fix needed)

idk why, i don't have access to the cloudflare (cc @tnix100)

**Comment by tnix100** [comment]
Is this able to be merged into 1.6 now?

**Review by tnix100 — APPROVED** [review]

**Pull request merged**
