### PR TITLE
Use bottom sheets for modals on mobile

### PR DESCRIPTION
**Pull request by mdwalters**
### Normal modal

Screen Shot 2024-01-22 at 21 13 56

Screen Shot 2024-01-22 at 21 08 27

### List modal

Screen Shot 2024-01-22 at 21 14 22

Screen Shot 2024-01-22 at 21 14 42

### Demonstration

[Screencast from 2024-01-22 12-49-26.webm](https://github.com/meower-media-co/Meower-Svelte/assets/67456566/626813a1-c31e-4de4-bc63-8551fa5cc643)

### CODE REVIEW

**Comment by showierdata9978** [comment]
Mod panel needs more room
image

**Comment by mdwalters** [comment]
> Mod panel needs more room image

yes thats what i'm working on

Screen Shot 2024-01-22 at 20 51 59

**Comment by mdwalters** [comment]
@zedsleepyhead @tnix100 @Bloctans pls review 😇

**Review by Bloctans — APPROVED** [review]
Approved

**Comment by mdwalters** [comment]
erm when review 🤓

**Review by showierdata9978 — CHANGES_REQUESTED** [review]
Exit Button is misaligned from the title. Partially clipped by android statusbar on Galaxy A14 5G.

**Comment by mdwalters** [comment]
> Exit Button is misaligned from the title. Partially clipped by android statusbar on Galaxy A14 5G.

urghh showier why did you have to say that

**Comment by showierdata9978** [comment]
> > Exit Button is misaligned from the title. Partially clipped by android statusbar on Galaxy A14 5G.
> 
> can't reproduce, maybe get a better phone?
> 
> Screen Shot 2024-01-26 at 13 41 31
>

**Comment by mdwalters** [comment]
> > > Exit Button is misaligned from the title. Partially clipped by android statusbar on Galaxy A14 5G.
> > 
> > 
> > can't reproduce, maybe get a better phone?
> > Screen Shot 2024-01-26 at 13 41 31
> 
> 

uh its doing its job qhar am i supposed to do

**Comment by mdwalters** [comment]
personally I think this is a skill issue on google's end

Screenshot 2024-01-28 19 08 01

**Review by showierdata9978 — APPROVED** [review]

**Pull request merged**
