### PR TITLE
Add MIT Licence

### PR DESCRIPTION
**Pull request by showierdata9978**

### CODE REVIEW

**Review by williamhorning — APPROVED** [review]

**Comment by showierdata9978** [comment]
Everyone MUST agree with this.
image

**Review by JoshAtticus — APPROVED** [review]

**Comment by JoshAtticus** [comment]
You have my permission

**Comment by MikeDev101** [comment]
LGTM.

**Review by MikeDev101 — APPROVED** [review]

**Review by tnix100 — APPROVED** [review]

**Review by Bloctans — APPROVED** [review]
yes

**Comment by showierdata9978** [comment]
@heyimocto approve

**Comment by theotherhades** [comment]
alg

**Comment by theotherhades** [comment]
should we use american spelling (license instead of licence) for consistency?

**Comment by williamhorning** [comment]
@theotherhades It isn't super important as of now but in the future I think we should try using British English spelling for everything possible unless we want to go with American (~~Freedom~~) English, which would also work

**Comment by tnix100** [comment]
image

**Review by CST1229 — APPROVED** [review]

**Review by ArrowAced — APPROVED** [review]

**Comment by tnix100** [comment]
Just waiting on silver, then we can merge.

**Comment by showierdata9978** [comment]
OH I FORGOT THAT I BLOCKED MD @mdwalters (getting profile)

**Comment by showierdata9978** [comment]
unblocked

**Review by silvxrcat — APPROVED** [review]

**Pull request merged**
