### PR TITLE
Switch to text area for linebreak support

### PR DESCRIPTION
**Pull request by JoshAtticus**
Switching from <input> to <textarea> allows the user to create linebreaks, and also resize the text area. Has been tested to work with all attributes of `<input>`.

Demos
Standard textarea
Resized textarea
Post with linebreaks

### CODE REVIEW

**Comment by Bloctans** [comment]
bruh why not my branch lol

its tnixandbloctans-finalfeatures

**Comment by JoshAtticus** [comment]
> bruh why not my branch lol
> 
> its tnixandbloctans-finalfeatures

Because I want it to be added sooner

**Comment by Bloctans** [comment]
> > bruh why not my branch lol
> > its tnixandbloctans-finalfeatures
> 
> Because I want it to be added sooner

couple issues
1. if we add to the main svelte then cst might make 903468609586958 changes to your code meaning i have to scrap my entire branch
2. ill just add the changes to my branch too

**Comment by JoshAtticus** [comment]
> > > bruh why not my branch lol
> > > its tnixandbloctans-finalfeatures
> > 
> > 
> > Because I want it to be added sooner
> 
> couple issues
> 
> 1. if we add to the main svelte then cst might make 903468609586958 changes to your code meaning i have to scrap my entire branch
> 2. ill just add the changes to my branch too

**No**
He will not make changes, and don't add it to your branch, because it isn't yours or tnix's change, It's my idea.

**Comment by Bloctans** [comment]
> > > > bruh why not my branch lol
> > > > its tnixandbloctans-finalfeatures
> > > 
> > > 
> > > Because I want it to be added sooner
> > 
> > 
> > couple issues
> > 
> > 1. if we add to the main svelte then cst might make 903468609586958 changes to your code meaning i have to scrap my entire branch
> > 2. ill just add the changes to my branch too
> 
> **No** He will not make changes, and don't add it to your branch, because it isn't yours or tnix's change, It's my idea.

well i guess i should create a pull for my branch anyways

**Comment by JoshAtticus** [comment]
> > > > > bruh why not my branch lol
> > > > > its tnixandbloctans-finalfeatures
> > > > 
> > > > 
> > > > Because I want it to be added sooner
> > > 
> > > 
> > > couple issues
> > > 
> > > 1. if we add to the main svelte then cst might make 903468609586958 changes to your code meaning i have to scrap my entire branch
> > > 2. ill just add the changes to my branch too
> > 
> > 
> > **No** He will not make changes, and don't add it to your branch, because it isn't yours or tnix's change, It's my idea.
> 
> well i guess i should create a pull for my branch anyways

**NO**
I said it's my change and idea, you can't just add it to your own branch.

**Comment by Bloctans** [comment]
> > > > > > bruh why not my branch lol
> > > > > > its tnixandbloctans-finalfeatures
> > > > > 
> > > > > 
> > > > > Because I want it to be added sooner
> > > > 
> > > > 
> > > > couple issues
> > > > 
> > > > 1. if we add to the main svelte then cst might make 903468609586958 changes to your code meaning i have to scrap my entire branch
> > > > 2. ill just add the changes to my branch too
> > > 
> > > 
> > > **No** He will not make changes, and don't add it to your branch, because it isn't yours or tnix's change, It's my idea.
> > 
> > 
> > well i guess i should create a pull for my branch anyways
> 
> **NO** I said it's my change and idea, you can't just add it to your own branch.

**pull from my branch to the main branch

**Comment by JoshAtticus** [comment]
> > > > > > > bruh why not my branch lol
> > > > > > > its tnixandbloctans-finalfeatures
> > > > > > 
> > > > > > 
> > > > > > Because I want it to be added sooner
> > > > > 
> > > > > 
> > > > > couple issues
> > > > > 
> > > > > 1. if we add to the main svelte then cst might make 903468609586958 changes to your code meaning i have to scrap my entire branch
> > > > > 2. ill just add the changes to my branch too
> > > > 
> > > > 
> > > > **No** He will not make changes, and don't add it to your branch, because it isn't yours or tnix's change, It's my idea.
> > > 
> > > 
> > > well i guess i should create a pull for my branch anyways
> > 
> > 
> > **NO** I said it's my change and idea, you can't just add it to your own branch.
> 
> **pull from my branch to the main branch

Ok, you can do that

**Comment by tnix100** [comment]
Let's settle this, @Bloctans there's an option on your branch to sync changes from the main branch, you can just do that if this is merged.

I cannot decide whether it will be merged, since I'm not really part of the svelte team, wait for CST to make a decision.

**Comment by Bloctans** [comment]
> Let's settle this, @Bloctans there's an option on your branch to sync changes from the main branch, you can just do that if this is merged.
> 
> I cannot decide whether it will be merged, since I'm not really part of the svelte team, wait for CST to make a decision.

i feel like im not gonna continue tnixandbloctans-finalfeatures so i turned it to a pull request

**Comment by Bloctans** [comment]
> > Let's settle this, @Bloctans there's an option on your branch to sync changes from the main branch, you can just do that if this is merged.
> > I cannot decide whether it will be merged, since I'm not really part of the svelte team, wait for CST to make a decision.
> 
> i feel like im not gonna continue tnixandbloctans-finalfeatures so i turned it to a pull request

(might continue in new branch later or after beta 6)

**Comment by JoshAtticus** [comment]
uh, @mdwalters, you pushed "delete pwa manifest" to this branch, undo please?

**Comment by JoshAtticus** [comment]
> ## Deploying with  [Cloudflare Pages](https://pages.dev)  Cloudflare Pages
> **Latest commit:**	`7012ce9`
> **Status:**	   Deploy successful!
> **Preview URL:**	https://e6a6646c.meower-svelte.pages.dev
> **Branch Preview URL:**	https://joshatticus-patch-1.meower-svelte.pages.dev
> [View logs](https://dash.cloudflare.com/?to=/:account/pages/view/meower-svelte/e6a6646c-06a3-4f75-ad27-6e4f69d90eae)

Lmao finally

**Comment by mdwalters** [comment]
> uh, @mdwalters, you pushed "delete pwa manifest" to this branch, undo please?
> 
> Edit: I did it myself

i shouldn't be allowed to touch repos

**Comment by JoshAtticus** [comment]
@CST1229

**Comment by JoshAtticus** [comment]
@tnix100 has confirmed this will be added in 1.4

**Pull request closed without merging**
