### PR TITLE
[1.9 (Hopefully)] New logo screen/intro animation

### PR DESCRIPTION
**Pull request by Bloctans**
The new logo/intro animation for the meower svelte client as we will no longer have the old starting animation (rip)

### CODE REVIEW

**Review by Bloctans — COMMENTED** [review]
yeah this probably works better
gonna have to wait for deploy tho

**Comment by tnix100** [comment]
> yeah this probably works better gonna have to wait for deploy tho

It's not going to change how the logo transitions a bit, but it'll remove an unnecessary element from the DOM once the client has loaded. Only problem is it still doesn't work...

I also just noticed that the new startup animation looks too small on mobile.

**Comment by Bloctans** [comment]
> > yeah this probably works better gonna have to wait for deploy tho
> 
> It's not going to change how the logo transitions a bit, but it'll remove an unnecessary element from the DOM once the client has loaded. Only problem is it still doesn't work...
> 
> I also just noticed that the new startup animation looks too small on mobile.

ive made it a bit better, should i remove the fadein?

**Comment by Bloctans** [comment]
uh

**Comment by showierdata9978** [comment]
Tbh i prefer the old one more

**Comment by Bloctans** [comment]
> Tbh i prefer the old one more

this is supposed to make it quicker to get onto meower
zed asked for this iirc

**Comment by showierdata9978** [comment]
I'm fine with fully removing it, and only connecting to the websocket when needed.
Connecting to the ws ASAP causes a deadlock

**Review by zedsleepyhead — APPROVED** [review]

**Pull request merged**
