### PR TITLE
1.7

### PR DESCRIPTION
**Pull request by tnix100**
This pull request is to manage everything for 1.7.

### CODE REVIEW

**Comment by tnix100** [comment]
I don't know why it has a lot of the above commits, all of those except the rounded corners one were merged into master already.

**Review by Bloctans — APPROVED** [review]
as long as it works i dont care

**Review by MikeDev101 — APPROVED** [review]

**Review by CST1229 — APPROVED** [review]

**Comment by tnix100** [comment]
Please do not merge this for now, there is a bug that makes it so new accounts that are registered through the main setup won't be taken to the OOBE (sometimes). Seems to be a race condition between going to /oobe and / being redirected to /home.

If someone's able to fix it for me, I'd appreciate it :)

**Comment by MikeDev101** [comment]
Converted to draft until we fix this bug

**Comment by CST1229** [comment]
i'm getting this error when connecting (it worked fine before)
image

**Comment by tnix100** [comment]
> i'm getting this error when connecting (it worked fine before) image

Yeah seems like that happens when the server is in repair mode, so that's another bug that needs to be fixed.

**Comment by MikeDev101** [comment]
> 

That was me putting the server in repair mode, try again

**Comment by CST1229** [comment]
works now

**Pull request merged**
