### PR TITLE
1.8 Release

### PR DESCRIPTION
**Pull request by tnix100**

### CODE REVIEW

**Comment by tnix100** [comment]
# CHANGELOG NEEDS TO BE COMPLETED!

**Comment by JoshAtticus** [comment]
pingu

**Comment by tnix100** [comment]
# Before merging
1. Run Prettier
2. Disable `beta` flag in `src/lib/urls.js`

**Review by zedsleepyhead — APPROVED** [review]
very awesome update

**Review by Bloctans — APPROVED** [review]
1.8 moment

**Review by HAZARD6896 — APPROVED** [review]
Absolutely based. Approved :D

**Comment by JoshAtticus** [comment]
why was I removed as a reviewer?

**Comment by tnix100** [comment]
> why was I removed as a reviewer?

whoops, you've been re-added as a reviewer

**Review by JoshAtticus — APPROVED** [review]
Screenshot 2023-10-25 at 10 12 20 am

**Review by CST1229 — APPROVED** [review]

**Review by showierdata9978 — APPROVED** [review]

**Pull request merged**
