### PR TITLE
New PR for group chats and inbox

### PR DESCRIPTION
**Pull request by tnix100**
Made a new PR for group chats and inbox, since last one was getting too messy.

Changes:
- Group chats (without member management or creating new chats, yet)
- Inbox
- Deleting/reporting posts
- Reporting users
- Viewing recent user posts

### CODE REVIEW

**Comment by Bloctans** [comment]
request time?

**Comment by Bloctans** [comment]
also can you host it on the testing site

**Comment by tnix100** [comment]
> also can you host it on the testing site

It's on https://svelte-test.tnix.software

**Comment by Bloctans** [comment]
weird, i dont see it

**Comment by Bloctans** [comment]
i dont see any updates

**Comment by Bloctans** [comment]
oh nvm, what updates didya do

**Comment by tnix100** [comment]
> oh nvm, what updates didya do

Not a lot, just some small bug fixes.

**Pull request merged**
